/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

public class Maximum {
	public Integer findMaxInt(Integer a,Integer b,Integer c) {
		Integer max=a;
		if(b.compareTo(max)>0)
			max=b;
		if(c.compareTo(max)>0)
			max=c;
		return max;
	}
    public static void main(String[] args) {
		System.out.println("Welcome");
	}
}
