/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

public class Maximum {
	public Integer findMaxInt(Integer a,Integer b,Integer c) {
		Integer max=a;
		if(b.compareTo(max)>0)
			max=b;
		if(c.compareTo(max)>0)
			max=c;
		return max;
	}
	public Float findMaxFloat(Float a,Float b,Float c) {
		Float max=a;
		if(b.compareTo(max)>0)
			max=b;
		if(c.compareTo(max)>0)
			max=c;
		return max;
	}
	public String findMaxString(String a,String b,String c) {
		String max=new String(a);
		if(b.compareTo(max)>0)
			max=new String(b);
		if(c.compareTo(max)>0)
			max=new String(c);
		return max;
	}
    public static void main(String[] args) {
		System.out.println("Welcome");
	}
}
