/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

import org.junit.Test;

import com.cg.Maximum;

import static org.junit.Assert.*;

public class MaximumTest {
	
}
